#!/usr/bin/env bash
# replace params as detailed in README.md
mongodump --archive --db <dbname> | mongorestore --host <dokku-hostname> --port <port> --username <username> --password <password> --drop --archive --db <dbname>
